name: Trigger the guardrails preview build in turbot.com

on:
  workflow_dispatch:

  push:
    branches-ignore: 
      - "main"

  pull_request:
    types: [opened]

env:
  PREVIEW_LINK: turbot-com-git-docs-guardrails
  PREVIEW_DOMAIN: turbot.vercel.app

jobs:
  update:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Repository Dispatch commit
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT }}
          repository: turbot/turbot.com
          event-type: build-guardrails-docs-preview
          client-payload: '{"ref": "${{ github.ref }}", "commit_ref": "${{ github.sha }}", "ref_name": "${{ github.ref_name }}", "commit": true}'

  comment-link:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' && github.event.action == 'opened' }}
    steps:
      - name: Repository Dispatch PR
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_PAT }}
          repository: turbot/turbot.com
          event-type: build-guardrails-docs-preview
          client-payload: '{"ref": "${{ github.ref }}", "commit_ref": "${{ github.event.pull_request.head.number }}", "ref_name": "${{ github.ref_name }}", "pull_request": true}'